
####################################################################################
# FILE trade_overnight.R
#
####################################################################################
#
#' Builds an equity curve based on a successive number of overnight trades
#'
#' A dataframe with a date column is provided.  Each row corresponds to a
#' potential stock trade, so there may be many rows with different stocks on
#' the same date.  At least two columns must be provided:  the overnight
#' return, and an estimate (yhat) of that return generated by some model.
#'
#'
#'
#' @param predmat     A dataframe or xts matrix containing a date column, a
#'                    prediction column (yhat) and an overnight returns colum.
#'                    The names of these columns should be specified with the
#'                    datecol, yhatcol and retcol arguments.
#'
#' @param maxposn     The maximum number of equally weighted simultaneous positions
#'                    to take for an overnight trade.
#'
#' @param maxweight   The maximum weight given to any trade.  This is important
#'                    to limit how large a position will be when only one or very
#'                    stocks are traded during one day.
#'
#' @param longthresh  The threshold above which a long trade is taken.  This
#'                    threshold is compared with the yhatcol value for this decision.
#'
#' @param shortthresh The threshold below which a short trade is taken.  This
#'                    threshold is compared with the yhatcol value for this decision.
#'                    NOT YET IMPLEMENTED!
#'
#' @param dateseries  An optional xts series (such as SPY or GSPC) that has all dates
#'                    the market is open.  This is used to fill in dates not present
#'                    in predmat to carry forward the equity curve.  This way, the
#'                    resulting equity curve can be plotted without any big
#'                    time frames missing. Default is NA (no dates provided)
#'
#' @param datacol     The column name in predmat containing the dates.  If
#'                    predmat is an xts matrix, this should be set to NA which
#'                    will result in taking the xts matrix dates instead.
#'
#' @param yhatcol     The column name in predmat with the predicted values (yhat).
#'
#' @param retcol      The column name in predmat with the overnight returns.  Note
#'                    that the assumed overnight return starts on the current date
#'                    (close of market) to the next day's sale.  The user must
#'                    ensure these returns are properly lagged to ensure there is
#'                    no lookahead bias.
#'
#' @return  Returns an xts matrix with the resulting equity curve.  The xts matrix
#'          dates will either correspond to the predmat dates only (dateseries = NA),
#'          or an outer merge of the predmat dates with the dates in dateseries,
#'          properly subsetted at the start and ending boundaries of predmat.
#'
#'          In addition to the equity curve, the matrix includes a column for the
#'          number of trades performed on each date (Ntrades), and the total number
#'          of stocks available to trade on each date (Allstocks).
#'
#' @export
#----------------------------------------------------------------------------------
trade_overnight <- function(predmat, maxposn = 1, maxweight = 0.2,
                            longthresh = 0.01, shortthresh = -100, dateseries = NA,
                            datecol = NA, yhatcol = "yhat", retcol = "rets") {

  # ###########  For code testing only ##########
  # library(xtsanalytics)
  # # Use embedded Earnings dataset to test...
  # predmat           = Earnings[1:3000, c("Ret1", "dtBuy")]
  # colnames(predmat) = c("rets", "date")
  # set.seed(123)     # Generate somewhat correlated yhat to rets
  # predmat$yhat      = predmat$rets + runif(n = nrow(predmat), min = -0.25, max = 0.25)
  # #plot(predmat$rets, predmat$yhat)
  # yhatcol           = "yhat"
  # retcol            = "rets"
  # datecol           = "date"
  # maxweight         = 0.2
  # maxposn           = 5
  # spy               = xts_data["2011", ]
  # dateseries        = spy
  # longthresh        = 0.15
  #
  # ####################

  #------------------------------------------------------------------
  # Ensure alldates contain dates, irrespective of class or format
  #------------------------------------------------------------------
  if(class(predmat) == "xts") alldates <- index(predmat)
  if(is.na(datecol)) alldates <- row.names(predmat) else
    alldates <- predmat[, datecol]

  alldates   <- unique(alldates)
  Ndates     <- length(alldates)
  if(Ndates < 1) stop("predmat does not contain valid dates!")

  results    <- emptyxts(cnames = c("rets", "Allstocks", "Ntrades"),
                         order.by = as.Date(alldates))

  #-----------------------------------------------------------------
  # MAIN LOOP:  Trade each stock as specified
  #-----------------------------------------------------------------
  for(i in 1:Ndates) {
    # Extract all rows on a given date, sort on yhat decreasing
    df        <- predmat[predmat[, datecol] == alldates[i], ]
    Allstocks <- nrow(df)

    # Sort & Select only if we have more stocks than maxposn
    if(Allstocks <= maxposn) {
      dfsub <- df
    } else {
      df2 <- df[order(df[, yhatcol], decreasing = TRUE), ]

      # Select the top trades, up to maxposn
      dfsub  <- df2[1:min(nrow(df2), maxposn), ]
    }

    # Filter those trades to ensure they exceed longthresh
    rowsel <- ifelse(as.numeric(dfsub[, yhatcol]) >= longthresh, TRUE, FALSE)
    dfsub  <- dfsub[rowsel, ]
    nlong  <- nrow(dfsub)

    #-------------------------------------------------------------
    # Trade the returns in dfsub, equal weighted or up to maxinv
    #-------------------------------------------------------------
    if(nlong == 0) {
      retsum <- 0
    } else {
      wt     <- min(maxweight, 1 / nlong)
      retsum <- wt * sum(dfsub[, retcol])
    }


    #----------------------------------------------------------
    # Build the results matrix
    #----------------------------------------------------------
    results[i, "rets"]      <- retsum
    results[i, "Allstocks"] <- Allstocks
    results[i, "Ntrades"]   <- nrow(dfsub)

  }

  #--------------------------------------------------
  # Calculate equity curve
  #--------------------------------------------------
  ec           <- cumprod_na(1 + results[, "rets"])
  colnames(ec) <- "Equity_Curve"
  ec           <- xtsbind(ec, results[, c("Allstocks", "Ntrades")])

  #--------------------------------------------------
  # Inner pad with dateseries if available
  #--------------------------------------------------
  if(!is.na(dateseries)[[1]]) {

    tf      <- paste0(index(first(ec)), "/", index(last(ec)))
    tfdates <- index(dateseries[tf,])

    ec           <- xtsbind(ec, tfdates)
    ec$Ntrades   <- ifelse(is.na(ec$Ntrades), 0, ec$Ntrades)
    ec$Allstocks <- ifelse(is.na(ec$Allstocks), 0, ec$Allstocks)
    ec           <- na.locf(ec, na.rm = TRUE)

  }

  return(ec)

}  ##############  END Function trade_overnight  #################
